import { Category, Product, StoreSettings, User, Shift, Sale, Expense, Customer, DebtPayment } from '../types';

export const initialCustomers: Customer[] = [
  {
    id: 'cust_1',
    name: 'محمد عبدالله الشناوي',
    phone: '01012345678',
    address: 'شارع التحرير - الدقي',
    totalDebt: 3500,
    notes: 'عميل دائم - دفع كل خميس',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust_2',
    name: 'محل البركة (أستاذ محمود)',
    phone: '01198765432',
    address: 'المعادي - شارع 9',
    totalDebt: 8200,
    notes: 'سحب بضاعة جملة آجل',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust_3',
    name: 'كابتن حسام حسن',
    phone: '01234567890',
    address: 'مدينة نصر - الحي السابع',
    totalDebt: 0,
    notes: 'حساب مسدد بالكامل',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialDebtPayments: DebtPayment[] = [];

export const initialStoreSettings: StoreSettings = {
  id: 'store_settings_singleton',
  storeName: 'Osama POS',
  storeAddress: 'شارع الجمهورية، وسط البلد، القاهرة',
  storePhone: '01001234567',
  storeEmail: 'contact@bayaa-pos.com',
  logoPath: '/assets/logo.png',
  taxNumber: '123-456-789',
  taxRate: 14,
  currency: 'EGP',
  invoicePrefix: 'INV',
  receiptFooter: 'شكراً لتعاملكم معنا - البضاعة المباعة ترد وتستبدل خلال 14 يوماً بالفاتورة',
  enableTax: false,
  lastInvoiceNumber: 1042,
};

export const initialUsers: User[] = [
  {
    id: 'admin',
    username: 'admin',
    displayName: 'مدير النظام (Admin)',
    role: 'manager',
    phone: '01001234567',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cashier',
    username: 'cashier',
    displayName: 'أحمد الكاشير (Ahmed)',
    role: 'cashier',
    phone: '01123456789',
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const initialCategories: Category[] = [
  { id: 'هواتف', name: 'هواتف ذكية', nameEn: 'Smartphones', color: '#2563eb', sortOrder: 1 },
  { id: 'إكسسوارات', name: 'إكسسوارات', nameEn: 'Accessories', color: '#7c3aed', sortOrder: 2 },
  { id: 'شواحن', name: 'شواحن وكابلات', nameEn: 'Chargers & Cables', color: '#059669', sortOrder: 3 },
  { id: 'سماعات', name: 'سماعات وصوتيات', nameEn: 'Audio & Earphones', color: '#d97706', sortOrder: 4 },
  { id: 'صيانة', name: 'قطع غيار وصيانة', nameEn: 'Spare Parts', color: '#dc2626', sortOrder: 5 },
];

export const initialProducts: Product[] = [
  {
    id: '111111',
    barcode: '111111',
    name: 'iPhone 13 Pro Max 256GB',
    price: 35000,
    wholesalePrice: 32000,
    cost: 32000,
    stock: 14,
    minStock: 3,
    categoryId: 'هواتف',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '222222',
    barcode: '222222',
    name: 'Samsung Galaxy S22 Ultra',
    price: 28000,
    wholesalePrice: 25000,
    cost: 25000,
    stock: 8,
    minStock: 2,
    categoryId: 'هواتف',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '333333',
    barcode: '333333',
    name: 'Apple AirPods Pro 2 MagSafe',
    price: 7500,
    wholesalePrice: 6500,
    cost: 6500,
    stock: 22,
    minStock: 5,
    categoryId: 'سماعات',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '444444',
    barcode: '444444',
    name: 'Anker PowerCore 20,000mAh',
    price: 1800,
    wholesalePrice: 1400,
    cost: 1400,
    stock: 2, // Low stock on purpose
    minStock: 5,
    categoryId: 'شواحن',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '555555',
    barcode: '555555',
    name: 'iPhone 14 Silicone Case (Original)',
    price: 450,
    wholesalePrice: 300,
    cost: 300,
    stock: 45,
    minStock: 10,
    categoryId: 'إكسسوارات',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '666666',
    barcode: '666666',
    name: 'Type-C to Lightning Cable 1.2m',
    price: 350,
    wholesalePrice: 200,
    cost: 200,
    stock: 0, // Out of stock on purpose
    minStock: 5,
    categoryId: 'شواحن',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '777777',
    barcode: '777777',
    name: 'شاشة أصلية iPhone 12 Pro OLED',
    price: 4200,
    wholesalePrice: 3500,
    cost: 3500,
    stock: 6,
    minStock: 2,
    categoryId: 'صيانة',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '888888',
    barcode: '888888',
    name: 'Joyroom Fast Charger 30W PD',
    price: 520,
    wholesalePrice: 390,
    cost: 390,
    stock: 18,
    minStock: 4,
    categoryId: 'شواحن',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp_1',
    title: 'إيجار المحل الشهري',
    amount: 6200,
    category: 'rent',
    notes: 'تم سداد دفعة الإيجار للمالك',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    userId: 'admin',
  },
  {
    id: 'exp_2',
    title: 'فاتورة الكهرباء والتكييف',
    amount: 1450,
    category: 'utilities',
    notes: 'إيصال الكهرباء الشهري',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    userId: 'admin',
  },
  {
    id: 'exp_3',
    title: 'أدوات تغليف وأكياس مطبوعة',
    amount: 430,
    category: 'supplies',
    notes: 'توريد كراتين وأكياس لوجو المحل',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    userId: 'admin',
  },
];

export const initialShifts: Shift[] = [
  {
    id: 'shift_current',
    userId: 'admin',
    userName: 'مدير النظام (Admin)',
    openTime: new Date(Date.now() - 4 * 3600000).toISOString(),
    openingCash: 1500,
    totalSales: 42950,
    totalCashSales: 35450,
    totalDebtCollectionsCash: 0,
    totalWalletSales: 7500,
    totalCreditSales: 0,
    totalRefunds: 0,
    totalExpenses: 430,
    expectedCash: 1500 + 35450 - 430,
    isOpen: true,
  },
  {
    id: 'shift_prev_1',
    userId: 'cashier',
    userName: 'أحمد الكاشير (Ahmed)',
    openTime: new Date(Date.now() - 28 * 3600000).toISOString(),
    closeTime: new Date(Date.now() - 18 * 3600000).toISOString(),
    closedBy: 'admin',
    openingCash: 1000,
    closingCash: 36450,
    expectedCash: 36450,
    cashDifference: 0,
    totalSales: 35450,
    totalCashSales: 35450,
    totalDebtCollectionsCash: 0,
    totalWalletSales: 0,
    totalCreditSales: 0,
    totalRefunds: 0,
    totalExpenses: 0,
    isOpen: false,
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale_1041',
    invoiceNumber: 'INV-1041',
    total: 35450,
    subtotal: 35450,
    tax: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    userId: 'admin',
    cashierName: 'مدير النظام (Admin)',
    itemsCount: 2,
    isRefund: false,
    shiftId: 'shift_current',
    paymentMethod: 'cash',
    cashReceived: 35500,
    changeGiven: 50,
    items: [
      {
        id: 'si_1',
        saleId: 'sale_1041',
        productId: '111111',
        productBarcode: '111111',
        productName: 'iPhone 13 Pro Max 256GB',
        quantity: 1,
        price: 35000,
        cost: 32000,
        wholesalePrice: 32000,
        subtotal: 35000,
        refundedQuantity: 0,
      },
      {
        id: 'si_2',
        saleId: 'sale_1041',
        productId: '555555',
        productBarcode: '555555',
        productName: 'iPhone 14 Silicone Case (Original)',
        quantity: 1,
        price: 450,
        cost: 300,
        wholesalePrice: 300,
        subtotal: 450,
        refundedQuantity: 0,
      },
    ],
  },
  {
    id: 'sale_1042',
    invoiceNumber: 'INV-1042',
    total: 7500,
    subtotal: 7500,
    tax: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    userId: 'admin',
    cashierName: 'مدير النظام (Admin)',
    itemsCount: 1,
    isRefund: false,
    shiftId: 'shift_current',
    paymentMethod: 'card',
    cardAmount: 7500,
    items: [
      {
        id: 'si_3',
        saleId: 'sale_1042',
        productId: '333333',
        productBarcode: '333333',
        productName: 'Apple AirPods Pro 2 MagSafe',
        quantity: 1,
        price: 7500,
        cost: 6500,
        wholesalePrice: 6500,
        subtotal: 7500,
        refundedQuantity: 0,
      },
    ],
  },
];
